name: sunamonir_pathshala
description: A Children Learning Application for Early Stage
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  audioplayers: ^5.2.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/images/sorborno/
   - assets/images/arabic/
   - assets/images/benjonborno/
   - assets/audios/sorborno/
   - assets/audios/benjonborno/
   - assets/images/mathematics/png/
   - assets/images/mathematics/numbers/
   - assets/images/mathematics/addition/
   - assets/images/mathematics/subtraction/
   - assets/images/mathematics/multiplication/
   - assets/images/mathematics/division/
   - assets/images/mathematics/akok/
   - assets/images/mathematics/compare/
   - assets/images/mathematics/serial/
   - assets/images/human_body/png/
   - assets/images/english/png/
   - assets/images/general_knowledge/png/
   - assets/images/general_knowledge/
   - assets/images/arabic/alphabets/
   - assets/images/arabic/surah_img/


  fonts:
    - family: Nikosh
      fonts:
        - asset: assets/fonts/Nikosh.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: 'Li SK Bishal'
      fonts:
        - asset: 'assets/fonts/Li SK Bishal Unicode.ttf'
    - family: Lato
      fonts:
        - asset: 'assets/fonts/Lato-Regular.ttf'
    - family: 'Uthmanic Script'
      fonts:
        - asset: 'assets/fonts/uthmanic_script.otf'


#  fonts:
#    - family: Nikosh
#      fonts:
#        - asset: assets/fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700